Models/Post.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace Mello.Models
{
    public class Post
    {
        [Key]
        public int Id { get; set; }

        public string? UserId { get; set; }
        public virtual User? User { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Type { get; set; }

      
        public string? Link { get; set; }

        [Required]
        public DateTime Date_created { get; set; }

        public virtual ICollection<Coment>? Comments{ get; set;} = new List<Coment>();
    }
}

Controllers/PostsController.cs
using Mello.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace WebApplication1.Controllers
{
    public class PostsController : Controller
    {
        private readonly AppDbContext db;

        private readonly UserManager<User> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        private IWebHostEnvironment _env;

        public PostsController(AppDbContext context,
                               UserManager<User> userManager,
                               RoleManager<IdentityRole> roleManager,
                               IWebHostEnvironment env)

        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }

        public IActionResult Index()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var user = db.Users.Find(userId);
            ViewBag.User = db.Users.Find(userId);


            var following = (from f in db.Follows
                             where f.Follower == user
                             select f.Following).ToList();

            following.Add(user);

            var posts = db.Posts
                        .Include("Comments")
                        .Include("User")
                        .Include("Comments.User")
                        .Where(post => following.Contains(post.User))
                        .OrderByDescending(post => post.Date_created);

            var search = "";
            IQueryable<User> users1 = null;

            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {

                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim();
                List<String> profiles = db.Users.Where(pf => pf.UserName.Contains(search)).Select(a => a.Id).ToList();
                users1 = db.Users.Where(profile => profiles.Contains(profile.Id));

            }
            ViewBag.SearchString = search;
            ViewBag.Profiles = users1;

            ViewBag.Posts = posts;

            if (User.IsInRole("Admin"))
            {
                ViewBag.Role = "Admin";
            }
            else if (User.IsInRole("User"))
            {
                ViewBag.Role = "User";
            }

            if (User.Identity.IsAuthenticated)
            {
                ViewBag.IsLoggedIn = true;
            }

            return View();
        }


        public IActionResult New()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> New(Post post, IFormFile? PostImage)
        {
            try
            {
                post.UserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                post.Date_created = DateTime.Now;
                if (post.Type == "Image" && PostImage.Length > 0)
                {
                    var storagePath = Path.Combine(_env.WebRootPath, "images", PostImage.FileName);
                    var databaseFileName = "/images/" + PostImage.FileName;
                    using (var fileStream = new FileStream(storagePath, FileMode.Create))
                    {
                        await PostImage.CopyToAsync(fileStream);
                    }
                    post.Link = databaseFileName;

                }
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            catch (Exception)
            {
                return RedirectToAction("New");
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Post post = db.Posts.Find(id);
            var coms = db.Coments.Where(com => com.PostId == id);
            foreach (var com in coms)
            {
                db.Coments.Remove(com);
            }
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int id)
        {
            Post post = db.Posts.Find(id);

            ViewBag.Post = post;

            return View();
        }

        // Se adauga articolul modificat in baza de date
        [HttpPost]
        public IActionResult Edit(int id, Post post)
        {
            Post post1 = db.Posts.Find(id);

            try
            {
                post1.Title = post.Title;
                post1.Description = post.Description;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Edit", id);
            }
        }

    }
}

Controllers/ProfileController.cs
using Mello.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Security.Claims;

namespace WebApplication1.Controllers
{
    public class ProfileController : Controller
    {
        private readonly AppDbContext db;

        private readonly UserManager<User> _userManager;

        private IWebHostEnvironment _env;

        private readonly RoleManager<IdentityRole> _roleManager;
        public ProfileController(AppDbContext context,
                               UserManager<User> userManager,
                               RoleManager<IdentityRole> roleManager,
                               IWebHostEnvironment env)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }
        public IActionResult Show(string id = "-1")
        {
            if(id == "-1")
            {
                id = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            }

            var user = db.Users.Find(id);
            ViewBag.User = user;
            var currentUser = db.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            ViewBag.CurrentUserId = currentUser.Id;
            Follow follow = new Follow();
            follow.Follower = currentUser;
            follow.Following = user;
            ViewBag.AlreadyFollows = db.Follows.Contains(follow);
            var follows = from f in db.Follows
                          where (f.Follower == currentUser) && (f.Following == user)
                          select f;
            ViewBag.AlreadyFollows = true;
            if(follows.Count() == 0)
            {
                ViewBag.AlreadyFollows = false;
            }
            var requested = from r in db.Requests
                            where (r.Requester == currentUser) && (r.Target == user)
                            select r;
            ViewBag.AlreadyRequested = true;
            if(requested.Count() == 0)
            {
                ViewBag.AlreadyRequested = false;
            }

            var posts = from p in db.Posts
                        where p.UserId == id
                        orderby p.Date_created descending
                        select p;



            ViewBag.Posts = posts.Include("Comments").Include("Comments.User");

            if (User.IsInRole("Admin"))
            {
                ViewBag.Role = "Admin";
            }

            return View();
        }

        public IActionResult Edit(string id)
        {
            var user = db.Users.Find(id);
            ViewBag.User = user;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, User requestUser, IFormFile? PostImage)
        {
            User user = db.Users.Find(id);
            //try
            //{
                user.UserName = requestUser.UserName;
                //user.NormalizedUserName = (requestUser.UserName).ToUpper();
                user.Email = requestUser.Email;
                user.NormalizedEmail = (requestUser.Email).ToUpper();
                user.PhoneNumber = requestUser.PhoneNumber;
                if (requestUser.Public == true)
                {
                    user.Public = true;
                }
                else
                {
                    user.Public = false;
                }

                if(PostImage == null && user.Link == null)
            {
                user.Link = null;
            }else if(PostImage == null && user.Link != null)
            {
                user.Link = user.Link;
            }

               else if (PostImage.Length > 0)
                {
                    var storagePath = Path.Combine(_env.WebRootPath, "images", PostImage.FileName);
                    var databaseFileName = "/images/" + PostImage.FileName;
                    using (var fileStream = new FileStream(storagePath, FileMode.Create))
                    {
                        await PostImage.CopyToAsync(fileStream);
                    }
                    user.Link = databaseFileName;

                }

                db.SaveChanges();
                return RedirectToAction("Show", new { id = id });
            //}
            //catch
            //{
            //    return RedirectToAction("Edit", new { id = id });
            //}
        }

        public IActionResult Follow(string id)
        {
            var targetUser = db.Users.Find(id);
            var currentUser = db.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);

            if (targetUser.Public == true)
            {
                Follow follow = new Follow();
                follow.Follower = currentUser;
                follow.Following = targetUser;
                db.Follows.Add(follow);
            }
            else
            {
                Request request = new Request();
                request.Requester = currentUser;
                request.Target = targetUser;
                db.Requests.Add(request);
            }
            db.SaveChanges();

            return RedirectToAction("Show", new { id = targetUser.Id });
        }

        public IActionResult Unfollow(string id) {
            var targetUser = db.Users.Find(id);
            var currentUser = db.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);

            var follow = from f in db.Follows
                          where (f.Follower == currentUser) && (f.Following == targetUser)
                          select f;

            db.Follows.Remove(follow.ToArray()[0]);
            db.SaveChanges();

            return RedirectToAction("Show", new { id = id });
        }

        public IActionResult ShowRequests(){
            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var requests = from r in db.Requests
                           where r.Target.Id == currentUserId
                           select r;

            ViewBag.Requests = requests.Include("Requester");

            return View();
        }

        public IActionResult AcceptRequest(string id)
        {
            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var requests = from r in db.Requests
                           where (r.Target.Id == currentUserId) && (r.Requester.Id == id)
                           select r;
            db.Requests.Remove(requests.ToArray()[0]);

            Follow follow = new Follow();
            follow.Follower = db.Users.Find(id);
            follow.Following = db.Users.Find(currentUserId);

            db.Follows.Add(follow);

            db.SaveChanges();

            return RedirectToAction("ShowRequests");
        }
    }
}

Views/Posts/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}




<form method="post" action="/Posts/Edit/@ViewBag.Post.Id">

    <div class="flex-container">
        <h2>Editeaza postarea</h2>
        <br />
        <label>Titlu articol</label>
        <input type="text" name="Title" value="@ViewBag.Post.Title" />
        <br />

        <label>Descriere postare</label>
        <textarea style="width:300px; min-height: 5em; max-height: 50vh;" name="Description">@ViewBag.Post.Description</textarea>
        <br />

        <button class="btn-grad" type="submit">Modifica Postarea</button>
    </div>


</form>

Views/Posts/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<form method="GET">
    <div class="input-group mb-3">
        <input style="" type="text" class="form-control" placeholder="Cauta utilizatori" name="search" value="@ViewBag.SearchString">
        <button style="margin: 0px" class="btn-grad" type="submit">Search</button>
    </div>
</form>

@if (!string.IsNullOrEmpty(ViewBag.SearchString))
{
    <div>Rezultatele pentru @ViewBag.SearchString:</div>
    @foreach (var user in ViewBag.Profiles)
    {
        <div><a href="@Url.Action("Show", "Profile", new { id = user.Id })">@user.UserName</a></div>
        <br />
    }
}
else
{
    <div class="flex-container">

    @foreach (var post in ViewBag.Posts)
    {

        <div class="card mb-3" style="max-width: 35rem">
            @if (post.Type == "Image")
            {
                <img class="card-img-top" src="@post.Link">
            }
            else if (post.Type == "Video")
            {
                <iframe width="560" height="315" src="@post.Link" frameborder="0" allowfullscreen></iframe>
            }
            <div class="card-body">
                <h4 class="card-title">@post.Title</h4>
                <h6>
                <a class="card-subtitle mb-2 text-muted" href="@Url.Action("Show", "Profile", new { id = post.User.Id })">@post.User.UserName</a>
                </h6>
                <div class="card-text">@post.Description</div>
                    <div class="d-flex flex-row justify-content-around">

                    @if (ViewBag.User != null)
                    {
                        @if (ViewBag.User.Id == post.UserId)
                        {
                            <a class="btn-grad" href="/Posts/Edit/@post.Id">Editeaza Postare</a>
                        }

                        @if (ViewBag.Role == "Admin" || (ViewBag.User.Id == post.UserId))
                        {
                            <form method="post" action="/Posts/Delete/@post.Id">
                                <button class="btn-grad-red" type="submit">Sterge Postarea</button>
                            </form>
                        }   
                    }

                </div>

            </div>
               <div class="card-footer flex-container">
                    @foreach(var comm in post.Comments)
                    {
                        <div class="card" style="width: 26rem;">
                            <div class="card-body">
                                <h6>
                                    <a class="card-subtitle mb-2 text-muted" href="@Url.Action("Show", "Profile", new { id = comm.User.Id })">@comm.User.UserName</a>
                                </h6>
                                <p class="card-text">@comm.Content</p>

                                <div class="d-flex flex-row justify-content-around">
                                    @if (ViewBag.User != null)
                                {
                                    @if (ViewBag.User.Id == comm.UserId)
                                    {
                                        <a class="btn-grad" href="/Coments/Edit/@comm.Id">Editeaza Comentariu</a>
                                    }

                                    @if (ViewBag.Role == "Admin" || (ViewBag.User.Id == comm.UserId) || ViewBag.User.Id == comm.UserId)
                                    {
                                        <form method="post" action="/Coments/Delete/@comm.Id">
                                            <button class="btn-grad-red" type="submit">Sterge comentariul</button>
                                        </form>
                                    }
                                }
                                </div>
                                
                            </div>
                        </div>
                    }


                    <div class="card" style="width: 26rem;">
                        <div class="card-body">
                            
                          <form method="post" action="/Coments/New">
                            <div class="card-body">
                                <input type="hidden" name="PostId" value="@post.Id" />
                                <label>Continut comentariu</label>
                                <br />
                                <textarea class="form-control" name="Content"></textarea>
                                <br />
                                <button class="btn-grad" type="submit">Adauga comentariul</button>
                            </div>
                        </form>

                        </div>
                    </div>


                    



                </div>
        </div>
    }

    </div>

    
    @if (ViewBag.IsLoggedIn == true)
    {
        <footer class="footer">
            <div style="border-top: 2px solid grey" class="d-flex justify-content-center">
                <a class="btn-grad" href="/Posts/New">Adauga Postare</a>
                <br />
                <a class="btn-grad" href="Groups/New">Adauga un grup</a>
                <br />
            </div>
        </footer>
    }
}

Views/Posts/New.cshtml
@{
    ViewBag.Title = "New";
}

<form enctype="multipart/form-data" asp-controller="Posts" asp-action="New">

    <div class="flex-container">
        <h2>Add post</h2>
        <label>Titlu Postare</label>
        <input type="text" name="Title" />
        <br />

        <label>Descrierie post</label>
        <textarea style="width:300px; min-height: 5em; max-height: 50vh;" name="Description"></textarea>
        <br />

        <label>Tip Postare</label>
        <select id="dropdown" name="Type" onchange="showContent()">
            <option value="Text"> Text</option>
            <option value="Image"> Image</option>
            <option value="Video"> Video</option>
        </select>
        <br />

        <style>
            .content {
                display: none;
            }
        </style>

        <div id="Image" class="content">
            <div>Incarca imaginea</div>
            <input type="file" name="PostImage" />
        </div>


        <div id="Video" class="content">
            <div>Introduce link-ul video-ului</div>
            <br/>
            <input type="text" name="Link"  />
        </div>

        <script>
            function showContent() {

                var dropdown = document.getElementById("dropdown");
                var selectedOption = dropdown.options[dropdown.selectedIndex].value;

                var contentDivs = document.querySelectorAll('.content');
                contentDivs.forEach(function (div) {
                    div.style.display = 'none';
                });

                var selectedDiv = document.getElementById(selectedOption);
                selectedDiv.style.display = "block";

                if (selectedOption == "Video" || selectedOption == "Image") {
                    var link = document.getElementById("linku");
                    link.style.display = "block";

                }
            }

        </script>
         <br />
        <button class="btn-grad" type="submit" value="Upload">Adauga post</button

    </div>


</form>